name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        docker build -t mycontainer:latest .
        echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login myregistry.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
        docker tag mycontainer:latest myregistry.azurecr.io/mycontainer:latest
        docker push myregistry.azurecr.io/mycontainer:latest

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: myResourceGroup
        dns-name-label: mydnslabel
        image: myregistry.azurecr.io/mycontainer:latest
        registry-login-server: myregistry.azurecr.io
        registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
