name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code s
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
        
    - name: Build and push Docker image
      run: |
        docker build -t mycontainer:latest .
        echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login containerregigor.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
        docker tag mycontainer:latest containerregigor.azurecr.io/mycontainer:latest
        docker push containerregigor.azurecr.io/mycontainer:latest

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: myResourceGroup
        dns-name-label: mydnslabel
        image: containerregigor.azurecr.io/mycontainer:latest
        registry-login-server: containerregigor.azurecr.io
        registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
